### ISSUE TITLE
Underworld is listed twice when clicking through world types when creating a new world

### ISSUE THREAD

**Issue by Roxforbraynz** [Matryoshika/Underworld#1]
Underworld 0.0.7
Forge 1.10.2 - 2056

Clicking through world types, you have to click twice to cycle past Underworld. This most likely means that it's listed twice.
I can provide my full modlist if you can't reproduce it.

**Comment by Matryoshika** [comment]
Will try to fix this.
For some reason, even just registering the WorldType once causes 2 WorldTypes to be selectable.
Might not be done before the next update.

**Comment by Matryoshika** [comment]
Closing issue as fixed.
See commit for more details.
