### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DaNeo61** [Matryoshika/Underworld#11]
Time Changes.

The current Time is Frozen to midnight.
it should be possible to change that with different Options like

Normal -> Vanilla Day / Time Cycle
Only Night -> Current State of Underworld
Only Day -> sounds stupid i know xD 
Cycle Night -> begins at 10 PM ends at 6am -> still night but time will change 

some mods are using the mc time like ae2 seed growth they crowth but very very slow at only midnight.

would be cool as Config Parameter

**Comment by charlesbevans** [comment]
I wonder how many other mods would be affected. I suppose it will mess with EU2's enderlilies. Maybe the fog could be set to black to hide the "daylight."

**Comment by Matryoshika** [comment]
I will likely add this to the next update. ETA just after new years.
Sickness, family & the upcoming holidays are taking it's toll.

**Comment by Matryoshika** [comment]
Closing issue, as Config for this has been added in version 0.2.12
:)
