### ISSUE TITLE
Question: Is this portal created by Underworld?

### ISSUE THREAD

**Issue by charlesbevans** [Matryoshika/Underworld#14]
I found this with only a couple of mods running. I don't think any of them make it.
![1015f3f2-c46f-11e6-8dba-36d1c646f8a6](https://cloud.githubusercontent.com/assets/15851438/21375081/fc410ace-c6df-11e6-849d-cc1d4181e571.png)

**Comment by Matryoshika** [comment]
No...
Underworld doesn't have anything to do with Nether Portals, or the Nether at all. Everything is completely custom, with worldgen similar, but code-wise, it doesn't touch Nether code at all...
What mods do you have installed?

**Comment by charlesbevans** [comment]
I was testing a few one at a time. At the time, I only had background stuff (JEI, JourneyMap, etc.) and WTF's Expedition. I'm going to use it for cave decoration and some custom oregen.
