### ISSUE TITLE
Guardians spawning like mad

### ISSUE THREAD

**Issue by Roxforbraynz** [Matryoshika/Underworld#2]
![Literally unplayable](http://i.imgur.com/vktmKSF.png)

I came across this which dropped my FPS to slideshow levels. This is not even one minute after using "/kill @e[type=Guardian]".

Seed: 4580877348786026862
Coords: X -43, Y 36, Z 148

**Comment by Matryoshika** [comment]
TileInvisMobSpawner works as it should; Stops spawning if there are more than 10 animals in a 4x4 chunk area.
Issue likely comes from my custom Ocean-Monument which at this time does not work. Disabled the initializeMap event-handler from overriding vanilla monuments at this time.

**Comment by Matryoshika** [comment]
As no more issues have been found these last 4 days, I'll see that as a victory over this bug :)
Please do reopen case you find a collection like this again.
