### ISSUE TITLE
Spawn platform in the nether

### ISSUE THREAD

**Issue by Roxforbraynz** [Matryoshika/Underworld#3]
![Self-explanatory](http://i.imgur.com/BzE2LW5.png)

The spawn platform generates in the nether. This was close to spawn, so I can't tell if it generates with the portal or if it generates at a fixed spot.

**Comment by Matryoshika** [comment]
Fixed in the next update:
The IWorldGenerator wasn't keyed to a certain dimension + worldtype.
Same goes for the dungeon + lilypad IWorldGenerators
