### ISSUE TITLE
Sugarcane is exceedingly rare, if not non-existant

### ISSUE THREAD

**Issue by Roxforbraynz** [Matryoshika/Underworld#4]
This potentially breaks other mods (e.g. Thaumcraft; not being able to get the Thauminomicon) as well as making enchanting nearly impossible.

**Comment by Matryoshika** [comment]
Already made sugarcane easier to get in the next update :)
Update should be uploaded to CurseForge within 1-2h.

**Comment by Matryoshika** [comment]
Closing issue.
Removed Sugarcane worldgen from 0.0.8, which was horrid due to Sugarcane's placement-requirements.
Added just now (0.0.10) the Sugarbeet, a custom crop like carrots & wheat, that is OreDictionaried with Sugarcane. You gain Sugarbeets by whacking grass :)
