### ISSUE TITLE
[1.10.2]  Server crash

### ISSUE THREAD

**Issue by kwpugh** [Matryoshika/Underworld#6]
Forge: 2053
Mod: underworld-1.10.2-0.0.9.jar

Crash report: http://pastebin.com/raw/WX7XgmBN

**Comment by Matryoshika** [comment]
Gah, damned IBlockState =_=
I'll remove the custom sugarcane worldgen, and implement my own custom sugarcane block variant instead, which doesn't have as many "can only exists here" restrictions.

It'll be in the next update that should be on CurseForge in ~12h

**Comment by Matryoshika** [comment]
Closing issue as the WorldGen function that caused this issue (DirtySugarcaneGen) was removed in 0.0.10, it's functionality replaced by Sugarbeets, a crop like carrots & wheat, which can be placed on dirt, grass & sand.
