### ISSUE TITLE
Brazier isn't craftable with charcoal

### ISSUE THREAD

**Issue by Roxforbraynz** [Matryoshika/Underworld#7]
The recipe for the brazier only accepts coal, limiting the amount of braziers that can be made and makes them more expensive as a decorative block.

Coal is a limited (albeit common) resource in the world and can be turned into blocks which are 11% more efficient as fuel compared to just using the coal itself or charcoal; Charcoal is cheaper and less valuable as fuel though it's a renewable resource which makes it more ideal for small amounts of smelting or crafting light sources (e.g. Torches).

**Comment by Matryoshika** [comment]
Charcoal will be added as a possible substitute in the upcoming update.
